config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :islands do
    resources :bookings, only: %i[new create show]
  end
  resources :bookings, only: %i[edit update index destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :island

  # validates :start_dates, presence: true
  # validates :end_dates, presence: true
  # validates :price, presence: true
  # validates :number_of_customers, presence: true
end

app/models/island.rb
class Island < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  validates :location, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :photos, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_location_and_name,
  against: [ :location, :name ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :islands
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_island, only: %i[new create]

  def index
    # @user = current_user
    # @bookings = Booking.all
    @bookings = current_user.bookings
  end

  def new
    @island = Island.find(params[:island_id])
    @booking = @island.bookings.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.island = @island
    # start_date = Date.strptime(params[:booking][:start_dates], '%d/%m/%Y')
    # end_date = Date.strptime(params[:booking][:end_dates], '%d/%m/%Y')
    # @booking = Booking.new(island_id: params[:booking][:island_id], start_dates: start_date, end_dates: end_date)
    @booking.user = current_user
    @booking_days = (@booking.end_dates - @booking.start_dates).to_i
    @booking.price = @island.price * @booking_days
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    authorize @booking
    # @booking = Booking.find(params[:id])
    # @island = @booking.island
    # @price = @island.price
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_dates, :end_dates, :price, :number_of_customers, :island_id, :user_id)
  end

  def set_island
    @island = Island.find(params[:island_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  before_action :set_island, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @islands = Island.search_by_location_and_name(params[:query])
    else
      @islands = Island.all
    end
  end

  def new
    @island = Island.new
  end

  def show
    @island = Island.find(params[:id])
  end

  def create
    @island = Island.new(island_params)
    @island.user = current_user
    if @island.save
      redirect_to islands_path(@island)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @island.update(island_params)
    redirect_to island_path(@island)
  end

  def destroy
    @island.destroy
    redirect_to islands_path, status: :see_other
  end

  private

  def set_island
    @island = Island.find(params[:id])
  end

  def island_params
    params.require(:island).permit(:location, :price, :name, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="main-container p-4" >
  <div class="card mx-auto bg-light" style="width: 50rem;">
    <div class="card-header text-center">
      <h4 class="card-title">Your trip :</h4>
        <%= simple_form_for [@island, @booking], data: { controller: 'flatpickr' } do |f| %>
  <%= f.input :start_dates, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
  <%= f.input :end_dates, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>
        <div class="form-group">
    <label for="exampleFormControlSelect1">Guests</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>1 guest</option>
      <option>2 guests</option>
      <option>3 guests</option>
      <option>4 guests</option>
      <option>5 guests</option>
      <option>6 guests</option>
      <option>7 guests</option>
      <option>8 guests</option>
      <option>9 guests</option>
      <option>10 guests</option>
        <br>
    </select>
  </div>
  <div class="form-group">
        <br>
        <%= f.submit class: "btn btn-secondary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="main-container p-4" >
<div class="card mx-auto" style="width: 55rem;">
    <div class="card-header text-center">
  <h1 class="mt-5 text-center">Thank you for your reservation ☺️</h1>
        <ul class="list-group">
        <% @bookings.each do |booking| %>
        <li class="list-group-item">
                  <%= booking.island.name %>,
                  <%= booking.island.location %>,
                  <%= booking.start_dates %>
                  <%= booking.end_dates  %>
                  $ <%= booking.price %></li>
      <br>

<% end %>
<p class="mt-5 text-center" ><%= link_to "Back to list", islands_path, class: "btn btn-success" %></p>
</div>
</div>
</div>

app/views/bookings/new.html.erb
<div class="main-container p-4" >
  <h2> <%= @island.name  %> </h2>
  <% if @island.photos.attached? %>
    <%= cl_image_tag @island.photos.first.key %>
  <% end %>
  <br>
  <div class="card-body d-flex flex-column justify-content-center align-items-center border-top">
    <%= render 'form', booking: @booking %>
  </div>
</div>

app/views/islands/edit.html.erb
<div class="container mt-4">
    <div class="row">
      <div class="col-6 m-auto">
        <div class="-form">
          <div class="edit mt-auto">
            <h1>Edit this Island 🏝️</h1>
            <%= simple_form_for(@island) do |f| %>
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :location %>
                <%= f.text_field :location, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :price %>
                <%= f.text_field :price, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.input :photos, as: :file, input_html: { multiple: true } %>
                </div>
              <div class="mt-3">
                <%= f.submit class: 'btn btn-info' %>
                <%= link_to 'Cancel', islands_path, class: 'btn btn-success ml-2' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/islands/index.html.erb
<div class="container py-5">
<div class="search-form col-12 col-sm-4 col-md-4">
  <%= form_with url: islands_path, method: :get, class: "d-flex w-100" do %>
    <div class="search-form-control form-group w-100">
    <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Type a keyword"
      %>
    <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>


  <div class="row">
    <% if @islands.any? %>
      <% @islands.each do |island| %>
        <div class="card-island col-12 col-sm-6 col-md-4 col-lg-3 mb-4 ">
          <div class="card-island-img">
            <% if island.photos.attached? %>
              <%= cl_image_tag island.photos.first.key, class: "card-img-top", height: 200, crop: :fill %>
            <% else %>
              <!-- You can add a placeholder image here if no photos are attached -->
              <%= image_tag "logo.png", class: "card-img-top", height: 200, alt: "Placeholder Image" %>
            <% end %>
            <div class="card-island-info">
              <h5 class="card-title"><%= island.name %></h5>
              <p class="card-text"><%= island.location %></p>
              <p class="card-text">$ <%= island.price %> by night </p>
              <a href="<%= island_path(island) %>" class="btn btn-secondary">View Details</a>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/islands/new.html.erb
 <div class="main-container">
    <div class="row">
      <div class="col-6 m-auto">
        <div class="-form ">
          <div class="mt-3 ">
            <h1>Add a new Island 🏝️</h1>
            <%= simple_form_for(@island) do |f| %>

              <div class="form-group">
                <%= f.label :name, label: "Enter your Island name:" %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :location, label: "Enter the location:" %>
                <%= f.text_field :location, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :price, label: "Enter the price per night: $" %>
                <%= f.text_field :price, class: 'form-control' %>
              </div>
                <br>
                <div class="form-group">
                  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
                </div>
              <div class="mt-3">
                <%= f.submit class: 'btn btn-secondary' %>
                <%= link_to 'Cancel', root_path(anchor: "recommandations"), class: 'btn btn-dark ml-2' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to islands_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
</div>

app/views/islands/show.html.erb
<div class="container">
  <div class="island-card-container">
    <div class="island-card d-flex">
      <div id="carouselExample" class="carousel slide">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <% if @island.photos.attached? %>
              <%= cl_image_tag(@island.photos.first.key, height: 300, width: 400, crop: :fill) %>
            <% end %>
          </div>
        <% @island.photos.each do |photo| %>
          <div class="carousel-item">
            <%= cl_image_tag(photo.key, height: 300, width: 400, crop: :fill) %>
          </div>
        <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

      <div class="island-top p-4">
        <div class="d-flex justify-content-between">
          <h2><%= @island.name %></h2>
          <div class="d-flex">
            <div class="mx-2">
              <%= link_to edit_island_path(@island) do %>
                <i class="fa-regular fa-pen-to-square"></i>
              <% end %>
            </div>
            <%= link_to island_path(@island), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?" } do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
          </div>
        </div>
        <div class="infos-card">
          <h2><%= @island.location %></h2>
          <p>Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>
          <p>Rating:⭐⭐⭐⭐⭐</p>
          <p>$<%= @island.price %> by night</p>
          <%= link_to "Book now", new_island_booking_path(@island[:id]), class: "btn btn-outline-primary" %>
        </div>
      </div>
    </div>
  </div>

  

  <%= link_to islands_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
</div>

app/views/layouts/application.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<!DOCTYPE html>
<html>
  <head>
    <title>IslandDream</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </head>

  <body>

    <%= render "shared/navbar" unless action_name == 'home'%>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render 'shared/footer' unless action_name == 'home' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#home</h1>
<%= link_to "list to islands",islands_path %>

app/views/pages/home.html.erb
<div class="video-container">
  <iframe src="https://streamable.com/e/p63vke?controls=0&autoplay=1&mute=1&playsinline=1&loop=1"></iframe>
</div>

<div class="overlay">
</div>

<div id="text">
  <h1>Island Dreams, <strong>make your dream</strong> a <strong>reality</strong>!</h1>
  <br>
  <p>Want to escape? book with us</p>
  <a class="btn btn-ghost" href="islands" style="color:white;">Discover our offers</a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by Island Dream
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to(root_path, class: "navbar-brand") do %>
      <img src="https://res.cloudinary.com/dmsz90kly/image/upload/v1698845999/logo_fbrkbj.png" />
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Rent island", new_island_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%# <%= link_to "My profil", user_session_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>